version: '3.8'
x-common:
  database:
    &db-environment
    MYSQL_PASSWORD: &db-password "m3oNyqMbwtr43o"
    MYSQL_ROOT_PASSWORD: "RfKww8iZTN6yTL"
  panel:
    &panel-environment
    APP_URL: "https://${PANEL_DOMAIN}"

    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "ignace.mella@telenet.be"
  mail:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

services:
  database:
    image: library/mysql:8.0
    restart: always
    networks:
      - local
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "${DATA_DIR}/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
  cache:
    image: redis:alpine
    restart: always
    networks:
      - local
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    networks:
      - local
      - proxy
    links:
      - database
      - cache
    volumes:
      - "${DATA_DIR}/panel/var/:/app/var/"
      - "${DATA_DIR}/panel/logs/:/app/storage/logs"
      - "${DATA_DIR}/panel/nginx/:/etc/nginx/conf.d/"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      TRUSTED_PROXIES: "*"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pterodactyl-panel.entrypoints=websecure"
      - "traefik.http.routers.pterodactyl-panel.rule=Host(`${PANEL_DOMAIN}`)"
      - "traefik.http.routers.pterodactyl-panel.service=pterodactyl"
      - "traefik.http.services.pterodactyl.loadbalancer.server.port=80"
networks:
  local:
    external: false
  proxy:
    external: true
