version: '3.8'
x-common:
  database:
    &db-environment
    MYSQL_PASSWORD: &db-password "m3oNyqMbwtr43o"
    MYSQL_ROOT_PASSWORD: "RfKww8iZTN6yTL"
  panel:
    &panel-environment
    APP_URL: "https://panel.mella.dev"

    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "ignace.mella@telenet.be"
  mail:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

services:
  database:
    image: library/mysql:8.0
    networks:
      - local
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/var/usr/pterodactyl/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    deploy:
      placement:
        constraints:
          - node.role == manager
  cache:
    image: redis:alpine
    networks:
      - local
    deploy:
      placement:
        constraints:
          - node.role == manager
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    networks:
      - local
      - public
    links:
      - database
      - cache
    volumes:
      - "/var/usr/pterodactyl/panel/var/:/app/var/"
      - "/var/usr/pterodactyl/panel/logs/:/app/storage/logs"
      - "/var/usr/pterodactyl/panel/nginx/:/etc/nginx/conf.d/"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      TRUSTED_PROXIES: "*"
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.pterodactyl-panel-http.rule=Host(`panel.mella.dev`)
        - traefik.http.routers.pterodactyl-panel-http.entrypoints=http
        - traefik.http.routers.pterodactyl-panel-http.middlewares=https-redirect
        - traefik.http.routers.pterodactyl-panel-https.rule=Host(`panel.mella.dev`)
        - traefik.http.routers.pterodactyl-panel-https.entrypoints=https
        - traefik.http.routers.pterodactyl-panel-https.tls=true
        - traefik.http.routers.pterodactyl-panel-https.tls.certresolver=le
        - traefik.http.services.pterodactyl-panel.loadbalancer.server.port=80
networks:
  local:
    external: false
  public:
    external: true
